name: Build and Commit Dist Files On Merge

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: rebuild
